version: '3'
services:
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:9000"
    volumes:
      - ./:/workspace
    ports:
      - "9000:9000"
